[package]
authors = ["Kevin Yeh <kevinyeah@utexas.edu>", "Saghm Rossi <saghmrossi@gmail.com>", "Valeri Karpov <valkar207@gmail.com>"]
description = "A native MongoDB driver for those who can't wait any longer (CWAL)"
documentation = "https://docs.rs/mongodb_cwal"
keywords = ["mongo", "mongodb", "database", "bson", "nosql"]
license = "Apache-2.0"
name = "mongodb_cwal"
readme = "README.md"
repository = "https://github.com/Devolutions/mongodb-cwal-rs"
version = "0.6.7"

[dependencies]
bitflags = "1.0.0"
bson = "0.14.0"
bufstream = "0.1.3"
byteorder = "1.0.0"
chrono = "0.4.0"
data-encoding = "2.0.0"
rand = "0.3.15"
scan_fmt = "0.1.1"
semver = "0.8.0"
serde = "1"
serde_derive = "1"
separator = "0.3.1"
time = "0.1.37"
md-5 = "0.7.0"
sha-1 = "0.7.0"
hmac = { path = "../MACs-hmac-v0.6.3" }
pbkdf2 = { path = "../password-hashes-pbkdf2-v0.2.3" }
hex = "0.3.2"
r2d2 = "0.8"
trust-dns-resolver = "0.12"

[dependencies.clippy]
optional = true
version = "~0"

[dependencies.openssl]
optional = true
version = "0.10.15"

[dependencies.serde_json]
version = "1"
features = ["preserve_order"]

[dependencies.textnonce]
default-features = false
version = "0.6.3"

[dev-dependencies]
approx = "0.1.1"

[features]
default = []
ssl = ["openssl"]
lint = ["clippy"]
