language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
    # tests if crates truly can be built without std
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
      install:
        - cargo install xargo --force
        - rustup target install armv7-unknown-linux-gnueabihf
        - rustup component add rust-src
      script: xargo build --verbose --target $TARGET

script:
  - cargo test --verbose --all --release --target $TARGET

cache: cargo
