[package]
name = "pbkdf2"
version = "0.2.3"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "Generic implementation of PBKDF2"
documentation = "https://docs.rs/pbkdf2"
repository = "https://github.com/RustCrypto/password-hashing"
keywords = ["crypto", "password", "hashing"]
categories = ["cryptography", "no-std"]

[dependencies]
crypto-mac = { path = "../traits-crypto-mac-v0.6.2" }
generic-array = "0.9"
byteorder = { version = "1", default-features = false }

rayon = { version = "1", optional = true }
constant_time_eq = { version = "0.1", optional = true }
base64 = { version = "0.9", optional = true }
rand = { version = "0.5", optional = true }
hmac = { path = "../MACs-hmac-v0.6.3", optional = true }
sha2 = { version = "0.7", optional = true }

[dev-dependencies]
hmac = { path = "../MACs-hmac-v0.6.3" }
sha-1 = "0.7"
sha2 = "0.7"

[features]
default = ["include_simple"]
parallel = ["rayon"]
include_simple = ["sha2", "hmac", "rand", "base64", "constant_time_eq"]

[badges]
travis-ci = { repository = "RustCrypto/password-hashing" }
